[package]

name = "async-smtp"
version = "0.1.0"
description = "SMTP client"
readme = "README.md"
homepage = "https://github.com/dignifiedquire/async-smtp"
repository = "https://github.com/dignifiedquire/async-smtp"
license = "Apache-2.0/MIT"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
categories = ["email"]
keywords = ["email", "smtp", "mailer"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "dignifiedquire/async-smtp" }
is-it-maintained-open-issues = { repository = "dignifiedquire/async-smtp" }

[dependencies]
log = "^0.4"
nom = { version = "^5.0", optional = true }
bufstream = { version = "^0.1", optional = true }
rustls = { version = "^0.16", optional = true }
base64 = { version = "^0.10", optional = true }
hostname = { version = "^0.1", optional = true }
serde = { version = "^1.0", optional = true }
serde_json = { version = "^1.0", optional = true }
serde_derive = { version = "^1.0", optional = true }
fast_chemail = "^0.9"
webpki-roots = "0.18.0"
rustls-connector = "0.8.1"
async-tls = { git = "https://github.com/async-rs/async-tls", branch = "refs" }
async-std = { git = "https://github.com/async-rs/async-std", features = ["unstable"] }
async-trait = "0.1.17"
snafu = "0.6.0"
pin-project = "0.4.5"
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
env_logger = "^0.6"
glob = "^0.3"
criterion = "^0.3"
async-attributes = "1.1.1"

[[bench]]
name = "transport_smtp"
harness = false

[features]
default = ["file-transport", "smtp-transport", "sendmail-transport"]
unstable = []
serde-impls = ["serde", "serde_derive"]
file-transport = ["serde-impls", "serde_json"]
smtp-transport = ["bufstream", "rustls", "base64", "nom", "hostname"]
sendmail-transport = []

[[example]]
name = "smtp"
required-features = ["smtp-transport"]

[[example]]
name = "smtp_gmail"
required-features = ["smtp-transport"]
